/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 6
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_create = 1,
  anon_sym_add = 2,
  anon_sym_to = 3,
  anon_sym_new = 4,
  anon_sym_link = 5,
  anon_sym_of = 6,
  anon_sym_purge = 7,
  anon_sym_as = 8,
  sym_dot = 9,
  sym_specification = 10,
  sym_string = 11,
  sym_source_file = 12,
  sym__instruction = 13,
  sym_keyword = 14,
  aux_sym_source_file_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_create] = "create",
  [anon_sym_add] = "add",
  [anon_sym_to] = "to",
  [anon_sym_new] = "new",
  [anon_sym_link] = "link",
  [anon_sym_of] = "of",
  [anon_sym_purge] = "purge",
  [anon_sym_as] = "as",
  [sym_dot] = "dot",
  [sym_specification] = "specification",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__instruction] = "_instruction",
  [sym_keyword] = "keyword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_create] = anon_sym_create,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_link] = anon_sym_link,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_purge] = anon_sym_purge,
  [anon_sym_as] = anon_sym_as,
  [sym_dot] = sym_dot,
  [sym_specification] = sym_specification,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__instruction] = sym__instruction,
  [sym_keyword] = sym_keyword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_create] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_link] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_purge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [sym_dot] = {
    .visible = true,
    .named = true,
  },
  [sym_specification] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 1,
        '.', 30,
        'a', 3,
        'c', 16,
        'l', 11,
        'n', 5,
        'o', 9,
        'p', 18,
        't', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(4);
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(2);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'g') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'k') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'w') ADVANCE(25);
      END_STATE();
    case 20:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(31);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_create);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_link);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_purge);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_dot);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_specification);
      if (lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_create] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_link] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_purge] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [sym_dot] = ACTIONS(1),
    [sym_specification] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(5),
    [sym__instruction] = STATE(2),
    [sym_keyword] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_create] = ACTIONS(5),
    [anon_sym_add] = ACTIONS(5),
    [anon_sym_to] = ACTIONS(5),
    [anon_sym_new] = ACTIONS(5),
    [anon_sym_link] = ACTIONS(5),
    [anon_sym_of] = ACTIONS(5),
    [anon_sym_purge] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [sym_dot] = ACTIONS(7),
    [sym_specification] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__instruction] = STATE(3),
    [sym_keyword] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_create] = ACTIONS(5),
    [anon_sym_add] = ACTIONS(5),
    [anon_sym_to] = ACTIONS(5),
    [anon_sym_new] = ACTIONS(5),
    [anon_sym_link] = ACTIONS(5),
    [anon_sym_of] = ACTIONS(5),
    [anon_sym_purge] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [sym_dot] = ACTIONS(11),
    [sym_specification] = ACTIONS(11),
    [sym_string] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__instruction] = STATE(3),
    [sym_keyword] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_create] = ACTIONS(15),
    [anon_sym_add] = ACTIONS(15),
    [anon_sym_to] = ACTIONS(15),
    [anon_sym_new] = ACTIONS(15),
    [anon_sym_link] = ACTIONS(15),
    [anon_sym_of] = ACTIONS(15),
    [anon_sym_purge] = ACTIONS(15),
    [anon_sym_as] = ACTIONS(15),
    [sym_dot] = ACTIONS(18),
    [sym_specification] = ACTIONS(18),
    [sym_string] = ACTIONS(18),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_create] = ACTIONS(21),
    [anon_sym_add] = ACTIONS(21),
    [anon_sym_to] = ACTIONS(21),
    [anon_sym_new] = ACTIONS(21),
    [anon_sym_link] = ACTIONS(21),
    [anon_sym_of] = ACTIONS(21),
    [anon_sym_purge] = ACTIONS(21),
    [anon_sym_as] = ACTIONS(21),
    [sym_dot] = ACTIONS(21),
    [sym_specification] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_akuro(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
